# Generated by Django 4.2.30 on 2026-06-02 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('cashierId', models.IntegerField(db_column='cashierId', primary_key=True, serialize=False)),
                ('fullName', models.CharField(db_column='fullName', max_length=255)),
            ],
            options={
                'db_table': 'cashier',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(db_column='categoryId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.CharField(db_column='customerId', max_length=20, primary_key=True, serialize=False)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('onlineOrderId', models.IntegerField(db_column='onlineOrderId', primary_key=True, serialize=False)),
                ('orderDatetime', models.DateTimeField(db_column='orderDatetime')),
                ('shippingProvince', models.CharField(db_column='shippingProvince', max_length=255)),
                ('orderStatus', models.CharField(db_column='orderStatus', max_length=255)),
                ('paymentMethod', models.CharField(db_column='paymentMethod', max_length=255)),
                ('customerId', models.ForeignKey(db_column='customerId', on_delete=django.db.models.deletion.CASCADE, to='ingestion.customer')),
            ],
            options={
                'db_table': 'onlineOrder',
            },
        ),
        migrations.CreateModel(
            name='PosTransaction',
            fields=[
                ('posTransactionId', models.IntegerField(db_column='posTransactionId', primary_key=True, serialize=False)),
                ('transactionDatetime', models.DateTimeField(db_column='transactionDatetime')),
                ('cashierId', models.ForeignKey(db_column='cashierId', on_delete=django.db.models.deletion.CASCADE, to='ingestion.cashier')),
            ],
            options={
                'db_table': 'posTransaction',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeId', models.IntegerField(db_column='storeId', primary_key=True, serialize=False)),
                ('storeName', models.CharField(db_column='storeName', max_length=255)),
                ('province', models.CharField(db_column='province', max_length=255)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productSKU', models.CharField(db_column='productSKU', max_length=20, primary_key=True, serialize=False)),
                ('productName', models.CharField(db_column='productName', max_length=255)),
                ('categoryId', models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, to='ingestion.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='PosTransactionLine',
            fields=[
                ('lineId', models.IntegerField(db_column='lineId', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('unitPrice', models.DecimalField(db_column='unitPrice', decimal_places=2, max_digits=10)),
                ('discountApplied', models.DecimalField(db_column='discountApplied', decimal_places=2, max_digits=10)),
                ('totalAmount', models.DecimalField(db_column='totalAmount', decimal_places=2, max_digits=10)),
                ('posTransactionId', models.ForeignKey(db_column='posTransactionId', on_delete=django.db.models.deletion.CASCADE, to='ingestion.postransaction')),
                ('productSKU', models.ForeignKey(db_column='productSKU', on_delete=django.db.models.deletion.CASCADE, to='ingestion.product')),
            ],
            options={
                'db_table': 'posTransactionLine',
            },
        ),
        migrations.AddField(
            model_name='postransaction',
            name='storeId',
            field=models.ForeignKey(db_column='storeId', on_delete=django.db.models.deletion.CASCADE, to='ingestion.store'),
        ),
        migrations.CreateModel(
            name='OnlineOrderLine',
            fields=[
                ('lineId', models.IntegerField(db_column='lineId', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('unitPrice', models.DecimalField(db_column='unitPrice', decimal_places=2, max_digits=10)),
                ('discountApplied', models.DecimalField(db_column='discountApplied', decimal_places=2, max_digits=10)),
                ('totalAmount', models.DecimalField(db_column='totalAmount', decimal_places=2, max_digits=10)),
                ('onlineOrderId', models.ForeignKey(db_column='onlineOrderId', on_delete=django.db.models.deletion.CASCADE, to='ingestion.onlineorder')),
                ('productSKU', models.ForeignKey(db_column='productSKU', on_delete=django.db.models.deletion.CASCADE, to='ingestion.product')),
            ],
            options={
                'db_table': 'onlineOrderLine',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryId', models.IntegerField(db_column='inventoryId', primary_key=True, serialize=False)),
                ('currentStockQty', models.IntegerField(db_column='currentStockQty')),
                ('reorderThreshold', models.IntegerField(db_column='reorderThreshold')),
                ('lastRestockedDate', models.DateField(db_column='lastRestockedDate')),
                ('productSKU', models.ForeignKey(db_column='productSKU', on_delete=django.db.models.deletion.CASCADE, to='ingestion.product')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='FeedbackSurvey',
            fields=[
                ('responseId', models.IntegerField(db_column='responseId', primary_key=True, serialize=False)),
                ('submissionDate', models.DateField(db_column='submissionDate')),
                ('satisfactionScore', models.PositiveSmallIntegerField(db_column='satisfactionScore')),
                ('npsScore', models.PositiveSmallIntegerField(db_column='npsScore')),
                ('productRating', models.PositiveSmallIntegerField(db_column='productRating')),
                ('deliveryRating', models.PositiveSmallIntegerField(db_column='deliveryRating')),
                ('freeTextComments', models.TextField(db_column='freeTextComments')),
                ('customerId', models.ForeignKey(db_column='customerId', on_delete=django.db.models.deletion.CASCADE, to='ingestion.customer')),
                ('onlineOrderId', models.ForeignKey(blank=True, db_column='onlineOrderId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.onlineorder')),
            ],
            options={
                'db_table': 'feedbackSurvey',
            },
        ),
        migrations.AddField(
            model_name='cashier',
            name='storeId',
            field=models.ForeignKey(db_column='storeId', on_delete=django.db.models.deletion.CASCADE, to='ingestion.store'),
        ),
        migrations.AddField(
            model_name='cashier',
            name='userId',
            field=models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
