# Generated by Django 4.2.30 on 2026-06-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_injectionjob_onlineinjectionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectionjob',
            name='rejected_rows',
            field=models.IntegerField(default=0),
        ),
    ]
